# Site settings
title: Terminal Overload
description: Terminal Overload is a home-made experimental free and open source multiplayer FPS game.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.terminal-overload.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

navigation:
 - title: Player Guide
   url: /playerguide
 - title: Community
   url: /community
 - title: Media
   url: /media
 - title: Contribute
   url: /contribute
 - title: FAQ
   url: /faq
 - title: Fund
   url: /fund
