# Site settings
title: Terminal Overload
description: Terminal Overload is a home-made experimental free and open source multiplayer FPS game.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://0.0.0.0:4000" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

navigation:
 - title: Home
   url: /index.html
 - title: Media
   url: /media/
 - title: FAQ
   url: /faq/       
 - title: Chat
   url: /chat/
 - title: Forum
   url: /forum/
