# Site settings
title: Terminal Overload
description: Terminal Overload the innovative, fast-paced, free and open source multiplayer FPS.
baseurl: "/terminal-overload.org/" # the subpath of your site, e.g. /blog/
url: "http://fr1tz.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
